using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SIAkademik.Domain.Enums;
using SIAkademik.Domain.ModulSiakad.Entities;
using SIAkademik.Domain.ValueObjects;
using SIAkademik.Infrastructure.Database.ValueConverters;

namespace SIAkademik.Infrastructure.ModulSiakad.EntityConfigurations;

internal class PegawaiEntityConfiguration : IEntityTypeConfiguration<Pegawai>
{
    public void Configure(EntityTypeBuilder<Pegawai> builder)
    {
        builder.HasKey(x => x.Id);
        builder.Property(x => x.NoHP).HasConversion<NoHPIntConverter>();
        builder.ComplexProperty(x => x.AlamatKTP, o =>
        {
            o.Property(y => y.Jalan).IsRequired();
            o.Property(y => y.RT).IsRequired();
            o.Property(y => y.RW).IsRequired();
            o.Property(y => y.KelurahanDesa).IsRequired();
            o.Property(y => y.Kecamatan).IsRequired();
            o.Property(y => y.KotaKabupaten).IsRequired();
            o.Property(y => y.Provinsi).IsRequired();
        });
        builder.HasOne(x => x.Account).WithOne(y => y.Guru).HasForeignKey<Pegawai>("AppUserId").IsRequired(false);
        builder.HasMany(x => x.DaftarRombelWali).WithOne(y => y.Wali);
        builder.HasMany(x => x.DaftarJadwalMengajar).WithOne(y => y.Pegawai);
        builder.HasOne(x => x.Divisi).WithMany(x => x.DaftarPegawai);
        builder.HasOne(x => x.Jabatan).WithMany(x => x.DaftarPegawai);

        builder.HasData(
            new
            {
                Id = "PJ24-003",
                Nama = "Mega Lita A. Lello, S.Pd",
                TanggalMasuk = new DateOnly(2024, 7, 1),
                JenisKelamin = JenisKelamin.Perempuan,
                TempatLahir = "Noelbaki",
                TanggalLahir = new DateOnly(2001, 7, 27),
                NoHP = NoHP.Create("081237731427").Value,
                Email = "megalello99@gmail.com",
                NIK = "5301086707010008",
                AlamatKTP_KodePos = "",
                AlamatKTP_Jalan = "Noelbaki",
                AlamatKTP_RT = 37,
                AlamatKTP_RW = 14,
                AlamatKTP_KelurahanDesa = "Kelurahan Noelbaki",
                AlamatKTP_Kecamatan = "Kupang Tengah",
                AlamatKTP_KotaKabupaten = "Kabupaten Kupang",
                AlamatKTP_Provinsi = "NTT",
                Agama = Agama.KristenProtestan,
                GolonganDarah = GolonganDarah.A,
                StatusPerkawinan = StatusPerkawinan.BelumKawin,
                NamaInstagram = string.Empty,
                NoRekening = "169601013554503(BRI)",
                JabatanId = 1,
                DivisiId = 1,
                AppUserId = 2
            },
            new
            {
                Id = "PJ14-004",
                Nama = "Johanis Oenunu, S.Si., M.M",
                TanggalMasuk = new DateOnly(2014, 07, 01),
                JenisKelamin = JenisKelamin.LakiLaki,
                TempatLahir = "Naikliu",
                TanggalLahir = new DateOnly(1990, 7, 18),
                NoHP = NoHP.Create("081353624462").Value,
                Email = "johanis@pandhegajaya.sch.id",
                NIK = "5371041807900001",
                AlamatKTP_KodePos = "",
                AlamatKTP_Jalan = "Jln. Gereja Moria",
                AlamatKTP_RT = 47,
                AlamatKTP_RW = 6,
                AlamatKTP_KelurahanDesa = "Kelurahan Liliba",
                AlamatKTP_Kecamatan = "Oebobo",
                AlamatKTP_KotaKabupaten = "Kota Kupang",
                AlamatKTP_Provinsi = "NTT",
                Agama = Agama.KristenProtestan,
                GolonganDarah = GolonganDarah.A,
                StatusPerkawinan = StatusPerkawinan.BelumKawin,
                NamaInstagram = "jo_oenunu1807",
                NoRekening = "3140785155 (BCA)",
                JabatanId = 2,
                DivisiId = 1,
                AppUserId = 4
            },
            new
            {
                Id = "PJ14-005",
                Nama = "Jeheskia Ngadirun, S.Th",
                TanggalMasuk = new DateOnly(2014, 7, 01),
                JenisKelamin = JenisKelamin.LakiLaki,
                TempatLahir = "Lampung",
                TanggalLahir = new DateOnly(1978, 5, 12),
                NoHP = NoHP.Create("082341108745").Value,
                Email = "jeheskia@pandhegajaya.sch.id",
                NIK = "5301081205780003",
                AlamatKTP_KodePos = "",
                AlamatKTP_Jalan = "Oelnasi",
                AlamatKTP_RT = 17,
                AlamatKTP_RW = 0,
                AlamatKTP_KelurahanDesa = "Desa Oelnasi",
                AlamatKTP_Kecamatan = "Kupang Tengah",
                AlamatKTP_KotaKabupaten = "Kabupaten Kupang",
                AlamatKTP_Provinsi = "NTT",
                Agama = Agama.KristenProtestan,
                GolonganDarah = GolonganDarah.A,
                StatusPerkawinan = StatusPerkawinan.BelumKawin,
                NamaInstagram = string.Empty,
                NoRekening = "7830-01-008243-53-7 (BRI)",
                JabatanId = 3,
                DivisiId = 1,
                AppUserId = 5
            },
            new
            {
                Id = "PJ18-012",
                Nama = "Ety Jelly Missa, S.Pd",
                TanggalMasuk = new DateOnly(2018, 7, 01),
                JenisKelamin = JenisKelamin.Perempuan,
                TempatLahir = "Kimadale",
                TanggalLahir = new DateOnly(1989, 3, 7),
                NoHP = NoHP.Create("085238664779").Value,
                Email = "etymissa0703@gmail.com",
                NIK = "5371044703890005",
                AlamatKTP_KodePos = "",
                AlamatKTP_Jalan = "Jln. El Tari",
                AlamatKTP_RT = 17,
                AlamatKTP_RW = 7,
                AlamatKTP_KelurahanDesa = "Kelurahan Naikoten Satu",
                AlamatKTP_Kecamatan = "Kota Raja",
                AlamatKTP_KotaKabupaten = "Kota Kupang",
                AlamatKTP_Provinsi = "NTT",
                Agama = Agama.KristenProtestan,
                GolonganDarah = GolonganDarah.A,
                StatusPerkawinan = StatusPerkawinan.BelumKawin,
                NamaInstagram = "etyjelly",
                NoRekening = "2502791721 (BANK NTT)",
                JabatanId = 4,
                DivisiId = 1,
                AppUserId = 47
            },
            new
            {
                Id = "PJ18-013",
                Nama = "Yonas Jangga Ratu, S.Pd., Gr",
                TanggalMasuk = new DateOnly(2018, 7, 01),
                JenisKelamin = JenisKelamin.LakiLaki,
                TempatLahir = "Makamenggit",
                TanggalLahir = new DateOnly(1991, 6, 22),
                NoHP = NoHP.Create("082339282852").Value,
                Email = "umbujonas22@gmail.com",
                NIK = "5311042206910004",
                AlamatKTP_KodePos = "",
                AlamatKTP_Jalan = "Padanjara",
                AlamatKTP_RT = 4,
                AlamatKTP_RW = 2,
                AlamatKTP_KelurahanDesa = "Kelurahan Makamenggit",
                AlamatKTP_Kecamatan = "Nggaha Ori Angu",
                AlamatKTP_KotaKabupaten = "Kabupaten Sumba Timur",
                AlamatKTP_Provinsi = "NTT",
                Agama = Agama.KristenProtestan,
                GolonganDarah = GolonganDarah.A,
                StatusPerkawinan = StatusPerkawinan.BelumKawin,
                NamaInstagram = "umbu_joven",
                NoRekening = "783001012234538 (BRI)",
                JabatanId = 5,
                DivisiId = 1,
                AppUserId = 6
            },
            new
            {
                Id = "PJ19-016",
                Nama = "Nerlan Konga Emu, S.Pd",
                TanggalMasuk = new DateOnly(2019, 7, 01),
                JenisKelamin = JenisKelamin.Perempuan,
                TempatLahir = "Barakaraha",
                TanggalLahir = new DateOnly(1999, 11, 19),
                NoHP = NoHP.Create("085338387302").Value,
                Email = "nerlanemu@pandhegajaya.sch.id",
                NIK = "5311046311990001",
                AlamatKTP_KodePos = "",
                AlamatKTP_Jalan = "Hamalinda",
                AlamatKTP_RT = 12,
                AlamatKTP_RW = 6,
                AlamatKTP_KelurahanDesa = "Kelurahan Makamenggit",
                AlamatKTP_Kecamatan = "Nggaha Ori Angu",
                AlamatKTP_KotaKabupaten = "Kabupaten Sumba Timur",
                AlamatKTP_Provinsi = "NTT",
                Agama = Agama.KristenProtestan,
                GolonganDarah = GolonganDarah.A,
                StatusPerkawinan = StatusPerkawinan.BelumKawin,
                NamaInstagram = "nerlanemu",
                NoRekening = "2176-01-013590-50-0 (BRI)",
                JabatanId = 6,
                DivisiId = 1,
                AppUserId = 7
            },
            new
            {
                Id = "PJ22-024",
                Nama = "Yefry O. M. Kuafeu, S.Pd., M.Sc., Gr",
                TanggalMasuk = new DateOnly(2022, 7, 01),
                JenisKelamin = JenisKelamin.LakiLaki,
                TempatLahir = "Oeleu",
                TanggalLahir = new DateOnly(1991, 7, 17),
                NoHP = NoHP.Create("081220042511").Value,
                Email = "yefrykuafeu@gmail.com",
                NIK = "5302271707910002",
                AlamatKTP_KodePos = "",
                AlamatKTP_Jalan = "Jl. Atambua No. 15",
                AlamatKTP_RT = 4,
                AlamatKTP_RW = 2,
                AlamatKTP_KelurahanDesa = "Kelurahan Pasir Panjang",
                AlamatKTP_Kecamatan = "Kota Lama",
                AlamatKTP_KotaKabupaten = "Kota Kupang",
                AlamatKTP_Provinsi = "NTT",
                Agama = Agama.KristenProtestan,
                GolonganDarah = GolonganDarah.A,
                StatusPerkawinan = StatusPerkawinan.BelumKawin,
                NamaInstagram = "Yefry_kuafeu",
                NoRekening = "0245-01-087347-50-8 (BRI)",
                JabatanId = 8,
                DivisiId = 1,
                AppUserId = 8
            },
            new
            {
                Id = "PJ22-026",
                Nama = "Sindi Pala Meha",
                TanggalMasuk = new DateOnly(2022, 7, 01),
                JenisKelamin = JenisKelamin.Perempuan,
                TempatLahir = "Lewa",
                TanggalLahir = new DateOnly(2003, 7, 6),
                NoHP = NoHP.Create("083147694407").Value,
                Email = "sndymeha55@gmail.com",
                NIK = "5311034607030002",
                AlamatKTP_KodePos = "",
                AlamatKTP_Jalan = "Lewa",
                AlamatKTP_RT = 7,
                AlamatKTP_RW = 3,
                AlamatKTP_KelurahanDesa = "Kelurahan Kambuhapang",
                AlamatKTP_Kecamatan = "Lewa",
                AlamatKTP_KotaKabupaten = "Kabupaten Sumba Timur",
                AlamatKTP_Provinsi = "NTT",
                Agama = Agama.KristenProtestan,
                GolonganDarah = GolonganDarah.A,
                StatusPerkawinan = StatusPerkawinan.BelumKawin,
                NamaInstagram = "sndy_meha",
                NoRekening = "0245-01-087347-50-8 (BRI)",
                JabatanId = 9,
                DivisiId = 1,
                AppUserId = (int?)null
            },
            new
            {
                Id = "PJ23-030",
                Nama = "Aprilando Mindeas Dibara Seran, S.Si",
                TanggalMasuk = new DateOnly(2023, 7, 1),
                JenisKelamin = JenisKelamin.LakiLaki,
                TempatLahir = "Kupang",
                TanggalLahir = new DateOnly(1999, 4, 18),
                NoHP = NoHP.Create("082117516199").Value,
                Email = "landoseran99@gmail.com",
                NIK = "5301081804990001",
                AlamatKTP_KodePos = "",
                AlamatKTP_Jalan = "Oepunu",
                AlamatKTP_RT = 17,
                AlamatKTP_RW = 8,
                AlamatKTP_KelurahanDesa = "Kelurahan Oelnasi",
                AlamatKTP_Kecamatan = "Kupang Tengah",
                AlamatKTP_KotaKabupaten = "Kabupaten Kupang",
                AlamatKTP_Provinsi = "NTT",
                Agama = Agama.KristenProtestan,
                GolonganDarah = GolonganDarah.A,
                StatusPerkawinan = StatusPerkawinan.BelumKawin,
                NamaInstagram = "landoseran04",
                NoRekening = "783001019682538",
                JabatanId = 10,
                DivisiId = 1,
                AppUserId = 9
            },
            new
            {
                Id = "PJ23-031",
                Nama = "Erika Vera Pandie, S.Pd",
                TanggalMasuk = new DateOnly(2023, 7, 1),
                JenisKelamin = JenisKelamin.Perempuan,
                TempatLahir = "Kupang",
                TanggalLahir = new DateOnly(1998, 9, 20),
                NoHP = NoHP.Create("081339600327").Value,
                Email = "ellapandie@gmail.com",
                NIK = "5371036009980003",
                AlamatKTP_KodePos = "",
                AlamatKTP_Jalan = "Lasiana",
                AlamatKTP_RT = 22,
                AlamatKTP_RW = 5,
                AlamatKTP_KelurahanDesa = "Kelurahan Lasiana",
                AlamatKTP_Kecamatan = "Kelapa Lima",
                AlamatKTP_KotaKabupaten = "Kota Kupang",
                AlamatKTP_Provinsi = "NTT",
                Agama = Agama.KristenProtestan,
                GolonganDarah = GolonganDarah.A,
                StatusPerkawinan = StatusPerkawinan.BelumKawin,
                NamaInstagram = "ellaapandie",
                NoRekening = "348801040709538",
                JabatanId = 11,
                DivisiId = 1,
                AppUserId = 10
            },
            new
            {
                Id = "PJ24-002",
                Nama = "Linda Janita Thine, S.Pd",
                TanggalMasuk = new DateOnly(2024, 7, 1),
                JenisKelamin = JenisKelamin.Perempuan,
                TempatLahir = "Oebelo",
                TanggalLahir = new DateOnly(2001, 1, 20),
                NoHP = NoHP.Create("082132253251").Value,
                Email = "lindajanitaa@gmail.com",
                NIK = "5314034401010002",
                AlamatKTP_KodePos = "",
                AlamatKTP_Jalan = "Lemulik",
                AlamatKTP_RT = 5,
                AlamatKTP_RW = 3,
                AlamatKTP_KelurahanDesa = "Kelurahan Kuli Aisele",
                AlamatKTP_Kecamatan = "Lobalain",
                AlamatKTP_KotaKabupaten = "Kabupaten Rote Ndao",
                AlamatKTP_Provinsi = "NTT",
                Agama = Agama.KristenProtestan,
                GolonganDarah = GolonganDarah.A,
                StatusPerkawinan = StatusPerkawinan.BelumKawin,
                NamaInstagram = "lnd8jnt",
                NoRekening = "361801040770534 (BRI)",
                JabatanId = 12,
                DivisiId = 1,
                AppUserId = 11
            },
            new
            {
                Id = "PJ24-004",
                Nama = "Sofia Blegur, S.H",
                TanggalMasuk = new DateOnly(2024, 7, 1),
                JenisKelamin = JenisKelamin.Perempuan,
                TempatLahir = "Lospalos",
                TanggalLahir = new DateOnly(1999, 6, 14),
                NoHP = NoHP.Create("081239270571").Value,
                Email = "sofiablegur14@gmail.com",
                NIK = "5305015406990001",
                AlamatKTP_KodePos = "",
                AlamatKTP_Jalan = "Manefeu",
                AlamatKTP_RT = 2,
                AlamatKTP_RW = 1,
                AlamatKTP_KelurahanDesa = "Kelurahan Baumata Timur",
                AlamatKTP_Kecamatan = "Taebenu",
                AlamatKTP_KotaKabupaten = "Kabupaten Kupang",
                AlamatKTP_Provinsi = "NTT",
                Agama = Agama.KristenProtestan,
                GolonganDarah = GolonganDarah.A,
                StatusPerkawinan = StatusPerkawinan.BelumKawin,
                NamaInstagram = "sofia_blegur",
                NoRekening = "786201008576539 (BRI)",
                JabatanId = 13,
                DivisiId = 1,
                AppUserId = 12
            },
            new
            {
                Id = "PJ24-005",
                Nama = "Paulinus Ferino, S.Pd",
                TanggalMasuk = new DateOnly(2024, 11, 6),
                JenisKelamin = JenisKelamin.LakiLaki,
                TempatLahir = "Watu Wogel",
                TanggalLahir = new DateOnly(1995, 8, 31),
                NoHP = NoHP.Create("082235773372").Value,
                Email = "putrolas@gmail.com",
                NIK = "5310130609950001",
                AlamatKTP_KodePos = "",
                AlamatKTP_Jalan = "Watuwogel",
                AlamatKTP_RT = 1,
                AlamatKTP_RW = 1,
                AlamatKTP_KelurahanDesa = "Kelurahan Satar Ruwuk",
                AlamatKTP_Kecamatan = "Satar Mese Barat",
                AlamatKTP_KotaKabupaten = "Kabupaten Manggarai",
                AlamatKTP_Provinsi = "NTT",
                Agama = Agama.Katolik,
                GolonganDarah = GolonganDarah.A,
                StatusPerkawinan = StatusPerkawinan.BelumKawin,
                NamaInstagram = string.Empty,
                NoRekening = "467701038760536 (BRI)",
                JabatanId = 14,
                DivisiId = 1,
                AppUserId = 13
            },
            new
            {
                Id = "PJ17-010",
                Nama = "Paulina Yane Tupu, S.Pd",
                TanggalMasuk = new DateOnly(2017, 2, 1),
                JenisKelamin = JenisKelamin.Perempuan,
                TempatLahir = "Waikabubak",
                TanggalLahir = new DateOnly(1989, 2, 15),
                NoHP = NoHP.Create("087765193550").Value,
                Email = "tupuyane@gmail.com",
                NIK = "5371035502890005",
                AlamatKTP_KodePos = "",
                AlamatKTP_Jalan = "Jln. Timor Raya",
                AlamatKTP_RT = 15,
                AlamatKTP_RW = 16,
                AlamatKTP_KelurahanDesa = "Kelurahan Oesapa",
                AlamatKTP_Kecamatan = "Kelapa Lima",
                AlamatKTP_KotaKabupaten = "Kota Kupang",
                AlamatKTP_Provinsi = "NTT",
                Agama = Agama.KristenProtestan,
                GolonganDarah = GolonganDarah.A,
                StatusPerkawinan = StatusPerkawinan.BelumKawin,
                NamaInstagram = "yane_tupu",
                NoRekening = "3140924066 (BCA)",
                JabatanId = 15,
                DivisiId = 2,
                AppUserId = 14
            },
            new
            {
                Id = "PJ14-003",
                Nama = "Samuel Pura Ngunju Meha, S. Pd, M.M",
                TanggalMasuk = new DateOnly(2014, 1, 1),
                JenisKelamin = JenisKelamin.LakiLaki,
                TempatLahir = "Makamenggit",
                TanggalLahir = new DateOnly(1986, 11, 18),
                NoHP = NoHP.Create("081138226931").Value,
                Email = "sam.meha@pandhegajaya.sch.id",
                NIK = "5371031811860003",
                AlamatKTP_KodePos = "",
                AlamatKTP_Jalan = "Jln. Timor Raya",
                AlamatKTP_RT = 14,
                AlamatKTP_RW = 5,
                AlamatKTP_KelurahanDesa = "Kelurahan Oesapa",
                AlamatKTP_Kecamatan = "Kelapa Lima",
                AlamatKTP_KotaKabupaten = "Kota Kupang",
                AlamatKTP_Provinsi = "NTT",
                Agama = Agama.KristenProtestan,
                GolonganDarah = GolonganDarah.A,
                StatusPerkawinan = StatusPerkawinan.BelumKawin,
                NamaInstagram = "sam_meha",
                NoRekening = "3140737291 (BCA)",
                JabatanId = 21,
                DivisiId = 6,
                AppUserId = 16
            },
            new
            {
                Id = "PJ19-017",
                Nama = "Yunias Lopes Beka, S.I.Kom",
                TanggalMasuk = new DateOnly(2019, 7, 1),
                JenisKelamin = JenisKelamin.LakiLaki,
                TempatLahir = "Naibonat",
                TanggalLahir = new DateOnly(2000, 7, 6),
                NoHP = NoHP.Create("081339638529").Value,
                Email = "yunias@pandhegajaya.sch.id",
                NIK = "5301060607000002",
                AlamatKTP_KodePos = "",
                AlamatKTP_Jalan = "Naibonat",
                AlamatKTP_RT = 20,
                AlamatKTP_RW = 7,
                AlamatKTP_KelurahanDesa = "Kelurahan Naibonat",
                AlamatKTP_Kecamatan = "Kupang Timur",
                AlamatKTP_KotaKabupaten = "Kabupaten Kupang",
                AlamatKTP_Provinsi = "NTT",
                Agama = Agama.KristenProtestan,
                GolonganDarah = GolonganDarah.A,
                StatusPerkawinan = StatusPerkawinan.BelumKawin,
                NamaInstagram = "yuniaslopesbeka",
                NoRekening = "4677 0104 6004 534 (BRI)",
                JabatanId = 7,
                DivisiId = 1,
                AppUserId = 17
            },
            new
            {
                Id = "PJ23-029",
                Nama = "Dusse Elma Botahala",
                TanggalMasuk = new DateOnly(2023, 7, 1),
                JenisKelamin = JenisKelamin.Perempuan,
                TempatLahir = "Fanating",
                TanggalLahir = new DateOnly(2003, 9, 2),
                NoHP = NoHP.Create("081237684620").Value,
                Email = "dussebotahala02@gmail.com",
                NIK = "5305014209030001",
                AlamatKTP_KodePos = "",
                AlamatKTP_Jalan = "Fanating",
                AlamatKTP_RT = 1,
                AlamatKTP_RW = 1,
                AlamatKTP_KelurahanDesa = "Kelurahan Fanating",
                AlamatKTP_Kecamatan = "Teluk Mutiara",
                AlamatKTP_KotaKabupaten = "Kabupaten Alor",
                AlamatKTP_Provinsi = "NTT",
                Agama = Agama.KristenProtestan,
                GolonganDarah = GolonganDarah.A,
                StatusPerkawinan = StatusPerkawinan.BelumKawin,
                NamaInstagram = "deb.yeol_",
                NoRekening = "350101045896530",
                JabatanId = 18,
                DivisiId = 1,
                AppUserId = 18
            }
        );
    }
}
