// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIAkademik.Infrastructure.Database;

#nullable disable

namespace SIAkademik.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250907120604_TambahJenisJabatan")]
    partial class TambahJenisJabatan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SIAkademik.Domain.Authentication.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppUser");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "ADMIN",
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "AQAAAAIAAYagAAAAEKXsR8woVHO5DgmyBgmfe5b4I7jeJZYtk71JFY4HkDSCsimeHtIwzOueTyHo8gBH/A==",
                            Role = "GURU",
                            UserName = "megalello99@gmail.com"
                        });
                });

            modelBuilder.Entity("SIAkademik.Domain.ModulSiakad.Entities.Absen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Absensi")
                        .HasColumnType("integer");

                    b.Property<int>("AnggotaRombelIdRombel")
                        .HasColumnType("integer");

                    b.Property<string>("AnggotaRombelNISN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Keterangan")
                        .HasColumnType("text");

                    b.Property<DateOnly>("Tanggal")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AnggotaRombelNISN", "AnggotaRombelIdRombel");

                    b.ToTable("TblAbsen");
                });

            modelBuilder.Entity("SIAkademik.Domain.ModulSiakad.Entities.AnggotaRombel", b =>
                {
                    b.Property<string>("NISN")
                        .HasColumnType("text");

                    b.Property<int>("IdRombel")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("TanggalKeluar")
                        .HasColumnType("date");

                    b.Property<DateOnly>("TanggalMasuk")
                        .HasColumnType("date");

                    b.HasKey("NISN", "IdRombel");

                    b.HasIndex("IdRombel");

                    b.ToTable("TblAnggotaRombel");
                });

            modelBuilder.Entity("SIAkademik.Domain.ModulSiakad.Entities.Divisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TblDivisi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nama = "SMA"
                        });
                });

            modelBuilder.Entity("SIAkademik.Domain.ModulSiakad.Entities.Jabatan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Jenis")
                        .HasColumnType("integer");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TblJabatan");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Jenis = 0,
                            Nama = "Guru Matematika"
                        });
                });

            modelBuilder.Entity("SIAkademik.Domain.ModulSiakad.Entities.JadwalMengajar", b =>
                {
                    b.Property<string>("NIP")
                        .HasColumnType("text");

                    b.Property<int>("IdMataPelajaran")
                        .HasColumnType("integer");

                    b.Property<int>("IdRombel")
                        .HasColumnType("integer");

                    b.Property<int>("Hari")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("JamMulai")
                        .HasColumnType("time without time zone");

                    b.HasKey("NIP", "IdMataPelajaran", "IdRombel");

                    b.HasIndex("IdMataPelajaran");

                    b.HasIndex("IdRombel");

                    b.ToTable("TblJadwalMengajar");
                });

            modelBuilder.Entity("SIAkademik.Domain.ModulSiakad.Entities.Kelas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Jenjang")
                        .HasColumnType("integer");

                    b.Property<int>("Peminatan")
                        .HasColumnType("integer");

                    b.Property<int>("TahunAjaranId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TahunAjaranId");

                    b.ToTable("TblKelas");
                });

            modelBuilder.Entity("SIAkademik.Domain.ModulSiakad.Entities.MataPelajaran", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Jenjang")
                        .HasColumnType("integer");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Peminatan")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TblMataPelajaran");
                });

            modelBuilder.Entity("SIAkademik.Domain.ModulSiakad.Entities.Nilai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnggotaRombelIdRombel")
                        .HasColumnType("integer");

                    b.Property<string>("AnggotaRombelNISN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Deskripsi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("JadwalMengajarIdMataPelajaran")
                        .HasColumnType("integer");

                    b.Property<int>("JadwalMengajarIdRombel")
                        .HasColumnType("integer");

                    b.Property<string>("JadwalMengajarNIP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Jenis")
                        .HasColumnType("integer");

                    b.Property<double>("Skor")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AnggotaRombelNISN", "AnggotaRombelIdRombel");

                    b.HasIndex("JadwalMengajarNIP", "JadwalMengajarIdMataPelajaran", "JadwalMengajarIdRombel");

                    b.ToTable("TblNilai");
                });

            modelBuilder.Entity("SIAkademik.Domain.ModulSiakad.Entities.Pegawai", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Agama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<int>("DivisiId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GolonganDarah")
                        .HasColumnType("integer");

                    b.Property<int>("JabatanId")
                        .HasColumnType("integer");

                    b.Property<int>("JenisKelamin")
                        .HasColumnType("integer");

                    b.Property<string>("NIK")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaInstagram")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NoHP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NoRekening")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatusPerkawinan")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("TanggalLahir")
                        .HasColumnType("date");

                    b.Property<DateOnly>("TanggalMasuk")
                        .HasColumnType("date");

                    b.Property<string>("TempatLahir")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty<Dictionary<string, object>>("AlamatKTP", "SIAkademik.Domain.ModulSiakad.Entities.Pegawai.AlamatKTP#Alamat", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Jalan")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Kecamatan")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("KelurahanDesa")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("KodePos")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("KotaKabupaten")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Provinsi")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("RT")
                                .HasColumnType("integer");

                            b1.Property<int>("RW")
                                .HasColumnType("integer");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.HasIndex("DivisiId");

                    b.HasIndex("JabatanId");

                    b.ToTable("TblPegawai");

                    b.HasData(
                        new
                        {
                            Id = "PJ24-003",
                            Agama = "Kristen Protestan",
                            AppUserId = 2,
                            DivisiId = 1,
                            Email = "megalello99@gmail.com",
                            GolonganDarah = 0,
                            JabatanId = 1,
                            JenisKelamin = 1,
                            NIK = "5301086707010008",
                            Nama = "Mega Lita A. Lello, S.Pd",
                            NamaInstagram = "",
                            NoHP = "081237731427",
                            NoRekening = "169601013554503(BRI)",
                            StatusPerkawinan = 1,
                            TanggalLahir = new DateOnly(2001, 7, 27),
                            TanggalMasuk = new DateOnly(2024, 7, 1),
                            TempatLahir = "Noelbaki"
                        });
                });

            modelBuilder.Entity("SIAkademik.Domain.ModulSiakad.Entities.Rombel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("KelasId")
                        .HasColumnType("integer");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WaliId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KelasId");

                    b.HasIndex("WaliId");

                    b.ToTable("TblRombel");
                });

            modelBuilder.Entity("SIAkademik.Domain.ModulSiakad.Entities.Siswa", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Agama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AgamaAyah")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AgamaIbu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AgamaWali")
                        .HasColumnType("text");

                    b.Property<string>("AktaKelahiran")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AnakKe")
                        .HasColumnType("integer");

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<string>("AsalSekolah")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("BeratBadan")
                        .HasColumnType("double precision");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GolonganDarah")
                        .HasColumnType("integer");

                    b.Property<string>("Hobi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HubunganDenganWali")
                        .HasColumnType("text");

                    b.Property<int>("JenisKelamin")
                        .HasColumnType("integer");

                    b.Property<int>("JumlahSaudara")
                        .HasColumnType("integer");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaAyah")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaIbu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaWali")
                        .HasColumnType("text");

                    b.Property<string>("NoHP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NoHPAyah")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NoHPIbu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NoHPWali")
                        .HasColumnType("text");

                    b.Property<string>("NomorKartuKeluarga")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PekerjaanAyah")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PekerjaanIbu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PekerjaanWali")
                        .HasColumnType("text");

                    b.Property<int>("Peminatan")
                        .HasColumnType("integer");

                    b.Property<string>("PendidikanTerakhirAyah")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PendidikanTerakhirIbu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PendidikanTerakhirWali")
                        .HasColumnType("text");

                    b.Property<int>("StatusHidupAyah")
                        .HasColumnType("integer");

                    b.Property<int>("StatusHidupIbu")
                        .HasColumnType("integer");

                    b.Property<int?>("StatusHidupWali")
                        .HasColumnType("integer");

                    b.Property<string>("Suku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("TanggalLahir")
                        .HasColumnType("date");

                    b.Property<DateOnly>("TanggalLahirAyah")
                        .HasColumnType("date");

                    b.Property<DateOnly>("TanggalLahirIbu")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("TanggalLahirWali")
                        .HasColumnType("date");

                    b.Property<string>("TempatLahir")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TinggiBadan")
                        .HasColumnType("double precision");

                    b.ComplexProperty<Dictionary<string, object>>("AlamatLengkap", "SIAkademik.Domain.ModulSiakad.Entities.Siswa.AlamatLengkap#Alamat", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Jalan")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Kecamatan")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("KelurahanDesa")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("KodePos")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("KotaKabupaten")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Provinsi")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("RT")
                                .HasColumnType("integer");

                            b1.Property<int>("RW")
                                .HasColumnType("integer");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("TblSiswa");
                });

            modelBuilder.Entity("SIAkademik.Domain.ModulSiakad.Entities.TahunAjaran", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Periode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TblTahunAjaran");
                });

            modelBuilder.Entity("SIAkademik.Domain.ModulSiakad.Entities.Absen", b =>
                {
                    b.HasOne("SIAkademik.Domain.ModulSiakad.Entities.AnggotaRombel", "AnggotaRombel")
                        .WithMany("DaftarAbsen")
                        .HasForeignKey("AnggotaRombelNISN", "AnggotaRombelIdRombel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnggotaRombel");
                });

            modelBuilder.Entity("SIAkademik.Domain.ModulSiakad.Entities.AnggotaRombel", b =>
                {
                    b.HasOne("SIAkademik.Domain.ModulSiakad.Entities.Rombel", "Rombel")
                        .WithMany("DaftarAnggotaRombel")
                        .HasForeignKey("IdRombel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIAkademik.Domain.ModulSiakad.Entities.Siswa", "Siswa")
                        .WithMany("DaftarAnggotaRombel")
                        .HasForeignKey("NISN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rombel");

                    b.Navigation("Siswa");
                });

            modelBuilder.Entity("SIAkademik.Domain.ModulSiakad.Entities.JadwalMengajar", b =>
                {
                    b.HasOne("SIAkademik.Domain.ModulSiakad.Entities.MataPelajaran", "MataPelajaran")
                        .WithMany("DaftarJadwalMengajar")
                        .HasForeignKey("IdMataPelajaran")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIAkademik.Domain.ModulSiakad.Entities.Rombel", "Rombel")
                        .WithMany("DaftarJadwalMengajar")
                        .HasForeignKey("IdRombel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIAkademik.Domain.ModulSiakad.Entities.Pegawai", "Pegawai")
                        .WithMany("DaftarJadwalMengajar")
                        .HasForeignKey("NIP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MataPelajaran");

                    b.Navigation("Pegawai");

                    b.Navigation("Rombel");
                });

            modelBuilder.Entity("SIAkademik.Domain.ModulSiakad.Entities.Kelas", b =>
                {
                    b.HasOne("SIAkademik.Domain.ModulSiakad.Entities.TahunAjaran", "TahunAjaran")
                        .WithMany("DaftarKelas")
                        .HasForeignKey("TahunAjaranId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TahunAjaran");
                });

            modelBuilder.Entity("SIAkademik.Domain.ModulSiakad.Entities.Nilai", b =>
                {
                    b.HasOne("SIAkademik.Domain.ModulSiakad.Entities.AnggotaRombel", "AnggotaRombel")
                        .WithMany("DaftarNilai")
                        .HasForeignKey("AnggotaRombelNISN", "AnggotaRombelIdRombel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIAkademik.Domain.ModulSiakad.Entities.JadwalMengajar", "JadwalMengajar")
                        .WithMany("DaftarNilai")
                        .HasForeignKey("JadwalMengajarNIP", "JadwalMengajarIdMataPelajaran", "JadwalMengajarIdRombel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnggotaRombel");

                    b.Navigation("JadwalMengajar");
                });

            modelBuilder.Entity("SIAkademik.Domain.ModulSiakad.Entities.Pegawai", b =>
                {
                    b.HasOne("SIAkademik.Domain.Authentication.AppUser", "Account")
                        .WithOne("Guru")
                        .HasForeignKey("SIAkademik.Domain.ModulSiakad.Entities.Pegawai", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIAkademik.Domain.ModulSiakad.Entities.Divisi", "Divisi")
                        .WithMany("DaftarPegawai")
                        .HasForeignKey("DivisiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIAkademik.Domain.ModulSiakad.Entities.Jabatan", "Jabatan")
                        .WithMany("DaftarPegawai")
                        .HasForeignKey("JabatanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Divisi");

                    b.Navigation("Jabatan");
                });

            modelBuilder.Entity("SIAkademik.Domain.ModulSiakad.Entities.Rombel", b =>
                {
                    b.HasOne("SIAkademik.Domain.ModulSiakad.Entities.Kelas", "Kelas")
                        .WithMany("DaftarRombel")
                        .HasForeignKey("KelasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIAkademik.Domain.ModulSiakad.Entities.Pegawai", "Wali")
                        .WithMany("DaftarRombelWali")
                        .HasForeignKey("WaliId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kelas");

                    b.Navigation("Wali");
                });

            modelBuilder.Entity("SIAkademik.Domain.ModulSiakad.Entities.Siswa", b =>
                {
                    b.HasOne("SIAkademik.Domain.Authentication.AppUser", "Account")
                        .WithOne("Siswa")
                        .HasForeignKey("SIAkademik.Domain.ModulSiakad.Entities.Siswa", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SIAkademik.Domain.Authentication.AppUser", b =>
                {
                    b.Navigation("Guru");

                    b.Navigation("Siswa");
                });

            modelBuilder.Entity("SIAkademik.Domain.ModulSiakad.Entities.AnggotaRombel", b =>
                {
                    b.Navigation("DaftarAbsen");

                    b.Navigation("DaftarNilai");
                });

            modelBuilder.Entity("SIAkademik.Domain.ModulSiakad.Entities.Divisi", b =>
                {
                    b.Navigation("DaftarPegawai");
                });

            modelBuilder.Entity("SIAkademik.Domain.ModulSiakad.Entities.Jabatan", b =>
                {
                    b.Navigation("DaftarPegawai");
                });

            modelBuilder.Entity("SIAkademik.Domain.ModulSiakad.Entities.JadwalMengajar", b =>
                {
                    b.Navigation("DaftarNilai");
                });

            modelBuilder.Entity("SIAkademik.Domain.ModulSiakad.Entities.Kelas", b =>
                {
                    b.Navigation("DaftarRombel");
                });

            modelBuilder.Entity("SIAkademik.Domain.ModulSiakad.Entities.MataPelajaran", b =>
                {
                    b.Navigation("DaftarJadwalMengajar");
                });

            modelBuilder.Entity("SIAkademik.Domain.ModulSiakad.Entities.Pegawai", b =>
                {
                    b.Navigation("DaftarJadwalMengajar");

                    b.Navigation("DaftarRombelWali");
                });

            modelBuilder.Entity("SIAkademik.Domain.ModulSiakad.Entities.Rombel", b =>
                {
                    b.Navigation("DaftarAnggotaRombel");

                    b.Navigation("DaftarJadwalMengajar");
                });

            modelBuilder.Entity("SIAkademik.Domain.ModulSiakad.Entities.Siswa", b =>
                {
                    b.Navigation("DaftarAnggotaRombel");
                });

            modelBuilder.Entity("SIAkademik.Domain.ModulSiakad.Entities.TahunAjaran", b =>
                {
                    b.Navigation("DaftarKelas");
                });
#pragma warning restore 612, 618
        }
    }
}
